server:
  port: 8082
spring:
  application:
    name: spring-boot-demo
  profiles:
    active: dev

feign:
  hystrix:
    enabled: true

eureka:
  client:
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5

## actuator 配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: ALWAYS

info:
  version: '@project.version@'

---
spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
... # "..."表示文档的结束

---
spring:
  profiles: prod
eureka:
  client:
    serviceUrl:
      defaultZone: http://ip:port/eureka/,http://ip:port/eureka/
...
