server:
  port: 8081

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/

management:
  security:
    enabled: false

spring:
  application:
    name: hello-service
  boot:
    admin:
      url: http://localhost:8080 #server端地址
    sleuth:
      sampler:
        percentage: 0.05  #采样率