server:
  port: 8082

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true

spring:
  application:
    name: hello-consumer
  boot:
    admin:
      url: http://localhost:8080 #server端地址
    sleuth:
      sampler:
        percentage: 0.05  #采样率

management:
  security:
    enabled: false