server:
  port: 8761

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: EUREKA-2
    prefer-ip-address: false # true为不使用主机名来定义注册中心的地址，而使用IP地址的形式 (实例名称显示IP配置)
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://EUREKA-1:8888/eureka/
