spring:
  profiles: dev

server:
  port: 8080

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/



logging:
  file: ./log/web-admin.log

info:
  version: @project.version@