spring:
  profiles: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/svili365/spring-cloud-demo
          searchPaths: configuration-lib
          #username:
          #password: